package persist

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// scheduledVersion is the on-disk format version for scheduled.json.
const scheduledVersion = 1

// ScheduledFile is the on-disk list of pending deferred transition mutations.
type ScheduledFile struct {
	Version int             `json:"version"`
	Items   []ScheduledItem `json:"items"`
}

// ScheduledItem is one pending deferred mutation. The defaults payload is
// resolved eagerly at schedule time and stored here, so cross-restart
// re-arm does not require the original request context.
//
// FilePath is stored RELATIVE to the runtime dir so a project directory
// move does not invalidate the schedule. Joined to absolute by the
// persister at save/load boundaries.
type ScheduledItem struct {
	ID              string          `json:"id"`
	Scope           string          `json:"scope"` // "rest" | "grpc"
	RouteKey        string          `json:"routeKey"`
	FilePath        string          `json:"filePath"`
	FireAt          time.Time       `json:"fireAt"`
	ResolvedPayload json.RawMessage `json:"resolvedPayload"`
	Source          string          `json:"source"`
}

// EmptyScheduled returns an initialised ScheduledFile with no items.
func EmptyScheduled() *ScheduledFile {
	return &ScheduledFile{Version: scheduledVersion, Items: []ScheduledItem{}}
}

// ItemsForScope returns the subset of items matching scope. Used at boot
// to feed each server's Rearm() method just the items it owns.
func (f *ScheduledFile) ItemsForScope(scope string) []ScheduledItem {
	if f == nil {
		return nil
	}
	out := make([]ScheduledItem, 0, len(f.Items))
	for _, it := range f.Items {
		if it.Scope == scope {
			out = append(out, it)
		}
	}
	return out
}

// ScheduledPersister wraps a scheduled.json path and the runtime dir the
// stored filePaths are relative to. Methods are safe for concurrent use.
type ScheduledPersister struct {
	path       string
	runtimeDir string
	mu         sync.Mutex
}

// NewScheduledPersister constructs a persister backed by path. runtimeDir
// is used to translate between absolute FilePath values (what the
// schedulers operate on) and the relative form stored on disk.
func NewScheduledPersister(path, runtimeDir string) *ScheduledPersister {
	return &ScheduledPersister{path: path, runtimeDir: runtimeDir}
}

// Load returns the current ScheduledFile with FilePaths rewritten to
// absolute form (rooted at the persister's runtimeDir). A missing file
// yields an empty file, not an error.
func (p *ScheduledPersister) Load() (*ScheduledFile, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.loadLocked()
}

func (p *ScheduledPersister) loadLocked() (*ScheduledFile, error) {
	data, err := os.ReadFile(p.path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return EmptyScheduled(), nil
		}
		return nil, fmt.Errorf("reading %q: %w", p.path, err)
	}
	var f ScheduledFile
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, fmt.Errorf("decoding %q: %w", p.path, err)
	}
	for i := range f.Items {
		if !filepath.IsAbs(f.Items[i].FilePath) {
			f.Items[i].FilePath = filepath.Join(p.runtimeDir, f.Items[i].FilePath)
		}
	}
	return &f, nil
}

// Add appends item to the persisted list. The FilePath is stored relative
// to runtimeDir on disk.
func (p *ScheduledPersister) Add(item ScheduledItem) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	f, err := p.loadLocked()
	if err != nil {
		return err
	}
	// Strip an empty id to an error — ids are generated by the scheduler.
	if strings.TrimSpace(item.ID) == "" {
		return fmt.Errorf("scheduled item requires non-empty id")
	}
	f.Items = append(f.Items, item)
	return p.saveLocked(f)
}

// Remove drops the item with the given id. Missing id is a no-op.
func (p *ScheduledPersister) Remove(id string) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	f, err := p.loadLocked()
	if err != nil {
		return err
	}
	kept := f.Items[:0]
	for _, it := range f.Items {
		if it.ID != id {
			kept = append(kept, it)
		}
	}
	f.Items = kept
	return p.saveLocked(f)
}

// Clear wipes the persisted list (used on hot-reload / full reset).
func (p *ScheduledPersister) Clear() error {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.saveLocked(EmptyScheduled())
}

// RemoveByScope drops all items matching the given scope. Used when one
// side (REST or gRPC) wants to wipe just its own pending items without
// affecting the other.
func (p *ScheduledPersister) RemoveByScope(scope string) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	f, err := p.loadLocked()
	if err != nil {
		return err
	}
	kept := f.Items[:0]
	for _, it := range f.Items {
		if it.Scope != scope {
			kept = append(kept, it)
		}
	}
	f.Items = kept
	return p.saveLocked(f)
}

func (p *ScheduledPersister) saveLocked(f *ScheduledFile) error {
	if f == nil {
		f = EmptyScheduled()
	}
	if f.Version == 0 {
		f.Version = scheduledVersion
	}
	// Rewrite absolute FilePaths to runtimeDir-relative for portability.
	toWrite := *f
	toWrite.Items = make([]ScheduledItem, len(f.Items))
	copy(toWrite.Items, f.Items)
	for i := range toWrite.Items {
		fp := toWrite.Items[i].FilePath
		if filepath.IsAbs(fp) && p.runtimeDir != "" {
			if rel, err := filepath.Rel(p.runtimeDir, fp); err == nil && !strings.HasPrefix(rel, "..") {
				toWrite.Items[i].FilePath = rel
			}
		}
	}
	data, err := json.MarshalIndent(&toWrite, "", "  ")
	if err != nil {
		return fmt.Errorf("encoding scheduled: %w", err)
	}
	return atomicWrite(p.path, data)
}
